name: locale_manager
description: "Flutter plugin to manage the locale of the native layer."
version: 0.0.2+1
repository: https://github.com/josecleiton/locale_manager
issue_tracker: https://github.com/josecleiton/locale_manager/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  plugin:
    platforms:
      android:
        package: br.com.josecleiton.locale_manager
        pluginClass: LocaleManagerPlugin
      ios:
        pluginClass: LocaleManagerPlugin